# Generated by Django 4.2.17 on 2024-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_equipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("muscle_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipment"},
        ),
    ]
