# Generated by Django 4.2.17 on 2025-01-03 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("application", "0003_muscle_alter_equipment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseRoutine",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("routine_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "estimated_time",
                    models.IntegerField(
                        help_text="Estimated time the routine takes in minutes."
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="The difficulty of the exercise routine.",
                    ),
                ),
                (
                    "routine_type",
                    models.CharField(
                        choices=[("Cardio", "Cardio"), ("Strength", "Strength")],
                        help_text="Type of routine.",
                        max_length=255,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Flag determining if this routine is public.",
                    ),
                ),
                (
                    "set_rest_time",
                    models.IntegerField(
                        default=45, help_text="Amount of rest between sets in seconds."
                    ),
                ),
                (
                    "exercise_rest_time",
                    models.IntegerField(
                        default=600,
                        help_text="Amount of rest between exercises in seconds.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineTargetMuscle",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("muscle", models.CharField(max_length=255)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.exerciseroutine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineTag",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=255)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.exerciseroutine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "exercise",
                    models.CharField(
                        help_text="The name of the exercise.", max_length=255
                    ),
                ),
                (
                    "reps",
                    models.IntegerField(
                        default=10, help_text="Number of reps (Strength only)."
                    ),
                ),
                (
                    "sets",
                    models.IntegerField(
                        default=3, help_text="Number of sets (Strength only)."
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=30,
                        help_text="Duration of the exercise in seconds (Cardio only).",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order of the exercise within the routine."
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.exerciseroutine",
                    ),
                ),
            ],
        ),
    ]
