# Generated by Django 4.2.17 on 2025-01-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_exerciseroutine_routinetargetmuscle_routinetag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineEquipment",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("equipment", models.CharField(max_length=255)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.exerciseroutine",
                    ),
                ),
            ],
        ),
    ]
