# Generated by Django 4.2.17 on 2025-01-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_alter_routineequipment_equipment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exerciseroutine",
            old_name="estimated_time",
            new_name="estimated_duration",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="muscle",
            name="muscle_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
